---
output: stevetemplates::cv
geometry: margin=0.55in

title: "CV"
author: Shilaan Alzahawi

# jobtitle: "Chief Brewer, Arthur Guinness & Son"
# address: "Guinness Brewery · Park Royal · London NW10 7RR, UK"
fontawesome: yes
email: shilaan@stanford.edu
github: shilaan
twitter: shilaan01
osf: ug7xd
# phone: "+353 1 408 4800"
web: shilaan.rbind.io
updated: FALSE
rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(fontawesome) #https://fontawesome.com/v5.15/icons?d=gallery&p=1
```                     


<!-- # Employment -->

<!-- *Arthur Guinness & Son* -->

<!-- Chief Brewer (Park Royal) \hfill 1935-1937 -->

<!-- Researcher (Dublin) \hfill 1899-1935 -->

# EDUCATION

**Graduate School of Business, Stanford University** \hfill Expected 2025  
PhD candidate in Organizational Behavior

**Faculty of Sciences, Ghent University** \hfill Expected 2022  
MSc in Statistical Science, Department of Applied Mathematics, Computer Science, and Statistics

**Rotterdam School of Management and Wharton School of Business** \hfill 2017  
MSc in Human Resource Management, *summa cum laude*

**Erasmus University Rotterdam** \hfill 2014  
BSc in Public Administration Science, Erasmus School of Social and Behavioral Sciences  
LLB in Law, Erasmus School of Law

# RESEARCH INTERESTS  

Team science; Crowd science; Meta-science; Statistical inference; Research rigor and reproducibility

# PUBLICATIONS

## JOURNAL ARTICLES

**Alzahawi, S.** & Monin, B. (2022). There Is No Psychology Without Inferential Statistics. *Behavioral and Brain Sciences, 45*, E2. [doi:10.1017/S0140525X2100056X](https://www.doi.org/10.1017/S0140525X2100056X)

Vani, P., **Alzahawi, S.**, Dannals, J., & Halevy, N. Strategic Mindsets and Support for Social Change: Impact Mindset Explains Support for Black Lives Matter across Racial Groups. Forthcoming at *Personality and Social Psychology Bulletin*.

Hoogeveen, S., Sarafoglou, A., Aczel, B., Aditya, Y., Alayan, A.J., Allen, P.J., Altay, S., **Alzahawi, S.**, ..., Van Elk, M., & Wagenmakers, E-J. A Many-Analysts Approach to the Relation between Religiosity and Well-being. Forthcoming at *Religion, Brain & Behavior*.

## OTHER PUBLICATIONS

**Alzahawi, S.** & Chandon, P. (2018). The Carrot Rewards Wellness App: Innovating in the Behavior Change Market. INSEAD Case Publishing. 

# PAPER UNDER REVIEW

Pownall, M., Azevedo, F., König, L.M., Slack, H.R., Evans, T., Flack, Z., Grinschgl, S., Elsherif, M., Gilligan-Lee, K., Oliveria, C.M., Gjoneska, B., Kanadadze, T., Button, K., Ashcroft-Jones, S., Terry, J., Albayrak-Aydemir, N., Valentine, Z., Děchtěrenko, F., **Alzahawi, S.**, ... The Impact of Open and Reproducible Scholarship on Students’ Scientific Literacy, Engagement, and Attitudes towards Science: A Review and Synthesis of the Evidence. Under Review at *Perspectives on Psychological Science*. 


# SELECTED RESEARCH IN PROGRESS

**Alzahawi, S.**, Reit, E.S., & Flynn, F.J. The (Missing) Link Between Ambition and Leader Effectiveness. 

**Alzahawi, S.** & Monin, B. Lay Perceptions of Scientific Findings: Swayed by the Crowd? Preregistration, data, code, materials, and reproducible working paper available at [osf.io/vedb4](https://osf.io/vedb4)

**Alzahawi, S.** Group-Wise Sequential Hypothesis Testing: Approaches and Trade-offs. Data, code, and reproducible working paper available at [osf.io/veczn](https://osf.io/veczn)

**Alzahawi, S.**, Loeys, T., & Monin, B. Power Analysis Tools for Mixed Effects Models. 

**Alzahawi, S.** Evaluating the Impact of Science Reforms.

**Alzahawi, S.** The Process of Discovery in Organizational Research: From Implicit Defaults to Active Choices.

Van Den Akker, O., Wicherts, J., Bakker, M., Van Assen, M., ... **Alzahawi, S.**, ... Assessing Preregistration Effectiveness.

Azevedo, F., Parsons, S., Micheli, L., Strand, J., ... **Alzahawi, S.**, ... Introducing a Framework for Open and Reproducible Research Training (FORRT). 

Jarke, H., Anand-Vembar, S.,  **Alzahawi, S.**, Andersen, T.L., Bojanić, L., Carstensen, A., Feldman, G., Garcia-Garzon, E., Kapoor, H., Lewis, S., Todsen, A.L., Većkalov, B., Zickfeld, J., & Geiger, S. A Roadmap to Large-Scale Multi-Country Replications in Psychology. 

Manley, H., Selvanathan, H.P., Vollhardt, J., **Alzahawi, S.**, ... The Effect of Sample Country on the Evaluation of Psychological Research.

Korbmacher, M., Hartmann, H., Elsherif, M.M., ... **Alzahawi, S.**, ... From Replicability Crisis to Credibility Revolution: Ways Forward in Psychological Research.

Tierney, W., Viganola, D., Ebersole, C., Hardy, J., ... **Alzahawi, S.**, Monin, B., ... Uhlmann, E.L. Replication Ring Examining the Robustness of Priming Effects on Judgments and Behaviors.

Tierney, W., Cyrus-Lai, W., ... **Alzahawi, S.**, Monin, B., ... Uhlmann, E.L. Who Respects an Angry Woman? A Preregistered Re-examination of the Relationships between Gender, Emotion Expression, and Status Conferral.

Delios, A., Clemente, E., Wu, T., Tan, H., Wang, Y., Gordon, M., Viganola, D., Chen, Z., Dreber, A., Johannesson, M., Pfeiffer, T., **Generalizability Tests Forecasting Collaboration**, & Uhlmann, E.L. Can You Step Into the Same River Twice? Examining the Context Sensitivity of Research Findings from Archival Data.

# PRESENTATIONS

## TALKS

Vani, P.\*, **Alzahawi, S.**, Dannals, J., & Halevy, N. (2022). *Impact Mindset Explains Support for Black Lives Matter across Racial Groups*. Paper to be presented at the Annual Meeting of the Academy of Management (AOM), Seattle. 

**Alzahawi, S.\*** (2022). *A Beginner's Guide to Version Control: Using GitHub in R*. Workshop to be presented at the Stanford Data Science for Social Good Program (DSSG), virtual. [`r fa("photo-video", fill = "#035AA6")`](https://shilaan.github.io/intro-github/)

**Alzahawi, S.\*** (2022). *A Beginner's Guide to Version Control: Using GitHub in R*. Workshop presented at the Stanford Center for Open and Reproducible Science (CORES) Spring Lecture Series, virtual. [`r fa("video", fill = "#035AA6")`](https://www.youtube.com/watch?v=6I-mAKAm6hM) [`r fa("photo-video", fill = "#035AA6")`](https://shilaan.github.io/intro-github/) 

**Alzahawi, S.\***, & Monin, B. (2022). *The Sway and Credibility of Crowd Science*. Paper presented at the Meta-Research Innovation Center at Stanford (METRICS) International Forum, virtual. [`r fa("video", fill = "#035AA6")`](https://stanford.zoom.us/rec/share/mLwfo-KvZjCvN01fcozmRp8UjN8d8eN0CmIzoIhnpzL960i6NXP5gynSGeU1cP1P.q5qoJ_KEaB8u9FvL?startTime=1646327040000)  [`r fa("photo-video", fill = "#035AA6")`](http://bit.ly/many-analysts) 

**Alzahawi, S.\***, & Monin, B. (2022). *The Sway and Credibility of Crowd Science*. Paper presented at the Toronto Workshop on Reproducibility, virtual.  [`r fa("video", fill = "#035AA6")`](https://www.youtube.com/watch?v=jynbJjTI10o) [`r fa("photo-video", fill = "#035AA6")`](http://bit.ly/many-analysts)  

Vani, P.\*, **Alzahawi, S.**, Dannals, J., & Halevy, N. (2022). *The Strategy of Social Change: Explaining Support for Black Lives Matter across Racial Groups*. Data blitz to be presented at SPSP, San Francisco. 

Hartmann, H.\*, Liu, M.\*, Elsherif, M.\*, **Alzahawi, S.\***, Aldoh, A.\*, Azevedo, F.\*, & Leech, G. (2021). *Replications & Reversals in Social Sciences*. Workshop presented at the Conference of the Association for Interdisciplinary Metaresearch and Open Science (aimos), virtual.

**Alzahawi, S.\*** (2021). *Writing Reproducible Manuscripts in R*. Workshop presented at the University of Amsterdam Lecture Series on Good Research Practices, The Netherlands. [`r fa("photo-video", fill = "#035AA6")`](https://shilaan-apa.netlify.app/#1) [`r fa("globe", fill = "#035AA6")`](https://shilaan.rbind.io/post/writing-reproducible-manuscripts-in-r/)

**Alzahawi, S.\*** (2021). *Writing Reproducible Manuscripts in R*. Workshop presented at the Stanford Center for Open and Reproducible Science (CORES) Fall Lecture Series, virtual. [`r fa("video", fill = "#035AA6")`](https://www.youtube.com/watch?v=LWcUjltWUNk) [`r fa("photo-video", fill = "#035AA6")`](https://shilaan-apa.netlify.app/#1) [`r fa("globe", fill = "#035AA6")`](https://shilaan.rbind.io/post/writing-reproducible-manuscripts-in-r/)

**Alzahawi, S.\***, & Monin, B. (2021). *The Sway and Credibility of Crowd Science*. Paper presented at the Psychological Science Accelerator Conference (PSACON), virtual. [`r fa("photo-video", fill = "#035AA6")`](http://bit.ly/many-analysts)   

**Alzahawi, S.\***, & Monin, B. (2021). *The Sway and Credibility of Crowd Science*. Paper presented at the Rising Scholars Conference, Harvard Business School, virtual. [`r fa("photo-video", fill = "#035AA6")`](http://bit.ly/many-analysts)   

**Alzahawi, S.\***, & Monin, B. (2021). *The Sway and Credibility of Crowd Science*. Paper presented at the Symposium on International Efforts to Improve Psychological Science, Taiwan Psychological Association, virtual. [`r fa("video", fill = "#035AA6")`](https://stanford.zoom.us/rec/play/9FRF6N_-FIMm4rkUK4MuVWAl4vzcOBENsugJFEJZSD6vtrcW_MD-X3xd6zAbm_wltsKIkHc3XQ5nlFYS.AQ9qjRzo7Dc9V2xp?startTime=1634127778000&_x_zm_rtaid=DCJsVP0gRsqfVJD9N-qxSQ.1643142404846.77bac81f2154d1a25b3dee3e781d0c3a&_x_zm_rhtaid=196)  [`r fa("photo-video", fill = "#035AA6")`](http://bit.ly/many-analysts) 

**Alzahawi, S.\*** (2021). *Writing Reproducible Manuscripts in R*. Workshop presented at the International Association for Conflict Management, virtual. [`r fa("photo-video", fill = "#035AA6")`](https://shilaan-apa.netlify.app/#1) [`r fa("globe", fill = "#035AA6")`](https://shilaan.rbind.io/post/writing-reproducible-manuscripts-in-r/)

Vani, P.\*, **Alzahawi, S.**, Dannals, J., & Halevy, N. (2021). *Support for Black Lives Matter across Racial Groups*. Paper presented at the International Association for Conflict Management, virtual.

**Alzahawi, S.\*** (2021). *Writing Reproducible Manuscripts in R*. Workshop presented at the Stanford Data Science for Social Good Program (DSSG), virtual. [`r fa("photo-video", fill = "#035AA6")`](https://shilaan-apa.netlify.app/#1) [`r fa("globe", fill = "#035AA6")`](https://shilaan.rbind.io/post/writing-reproducible-manuscripts-in-r/)

**Alzahawi, S.\*** (2021). *Writing Reproducible Manuscripts in R*. Workshop presented at the Stanford Center for Open and Reproducible Science (CORES) launch event, virtual. [`r fa("photo-video", fill = "#035AA6")`](https://shilaan-apa.netlify.app/#1) [`r fa("globe", fill = "#035AA6")`](https://shilaan.rbind.io/post/writing-reproducible-manuscripts-in-r/)

Halevy, N.\*, **Alzahawi, S.**, & Dannals, J. (2019). *Strategic Thinking in Everyday Life: A Social-Cognitive Approach*. Paper presented at the International Association for Conflict Management, Dublin, Ireland. 

Halevy, N.\*, **Alzahawi, S.**, & Dannals, J. (2019). *Strategic Thinking in Everyday Life: A Social-Cognitive Approach*. Paper presented at the International Conference on Social Dilemmas, Sedona, AZ. 

\* indicates presenter

## CHAIRED SYMPOSIUM

**Alzahawi, S.**, Greer, L., & Neale, M.A. (2019). *The Future of Negotiations Research*. Academy of Management, Boston, MA. Selected as Showcase Symposium (top 10%). 

## PANEL DISCUSSIONS

Panelist, *Open Update: UNESCO Recommendation on Open Science*. Panel discussion at Liberate Science's weekly podcast on the Open Science space, virtual.  

Panelist, *Multi-Country Replications: Approaches to Multi-Country Replications in Psychology and Behavioural Sciences*. Panel discussion at the Junior Researcher Program Conference, virtual.  

# TEACHING EXPERIENCE

Head Teaching Assistant, Managing Groups and Teams, Stanford MBA \hfill Fall 2022  
Head Mentor, Data Science for Social Good Program, Stanford Data Science \hfill Spring-Summer 2022   
Managing Groups and Teams, Stanford MBA \hfill Fall 2019, Fall 2021  
Mentor, Data Science for Social Good Program, Stanford Data Science \hfill Spring-Summer 2021  
Acting with Power, Stanford MBA \hfill Spring 2021  
Data and Decisions, Stanford MBA \hfill Winter 2020  
Conflict Management and Negotiations, Stanford MBA, MSx \hfill Fall 2020, Winter 2020  
Innovating in the Behavior Change Market, INSEAD MBA \hfill Spring 2018  
International Relations, Erasmus University College \hfill Summer 2015  
Foundations of Law, Erasmus University College \hfill Spring 2015  
Qualitative Research II: Content Analysis, Erasmus University College \hfill Spring 2015  
Qualitative Research I: Interviews, Erasmus University College \hfill Winter 2014  
Highlights of Sociology, Erasmus University College \hfill Winter 2014  
Introduction to Psychology, Erasmus University College \hfill Fall 2014  

# FELLOWSHIPS, HONORS, AWARDS

SPSP Graduate Student Poster Award [`r fa("globe", fill = "#035AA6")`](http://bit.ly/crowd-poster)  [`r fa("video", fill = "#035AA6")`](https://stanford.zoom.us/rec/share/mmIh1DF4lE37oI3_1SdmfZkVbtSUSp89xFKKSr_5z0EitC9rMlY-dupXziHCszsY.1rNzL38JsVSnXMmH)  \hfill 2022  
SPSP Graduate Travel Award \hfill 2022  
Mr. and Mrs. Alfonsi Business School Fund Fellowship \hfill 2021  
Master Mind Scholarship, Flemish Ministry of Education and Training \hfill 2021  
Open Science Innovator Award, Stanford Center for Open and Reproducible Science \hfill 2021  
Dataquest & AI Inclusive Data Science Scholarship \hfill 2020  
Jonsson Family Fellowship Fund \hfill 2020  
Showcase Symposium (top 10%), Academy of Management \hfill 2019  
Dave Mans and Jim Willenborg Fellowship Fund \hfill 2019  
Kaneko/Lainovic International Fellowship Fund \hfill 2019  
Stanford Graduate School of Business Fellowship \hfill 2018  
Best Case Award, EFMD Global Case Writing Competition \hfill 2018  
Highest Honors, Rotterdam School of Management \hfill 2017  
Prins Bernhard Cultuurfonds Research Fund \hfill 2017  
Stichting Vreedefonds Research Fund \hfill 2017  
Erasmus Happiness Economics Thesis Fund \hfill 2016  
Certificate of Recognition, Erasmus University Rotterdam \hfill 2014  

# ACADEMIC SERVICE, VOLUNTEERING, AND CONSULTING

Transform to Open Science (TOPS) Curriculum Development Team Lead, NASA \hfill 2022-present  
Executive Committee Member (Ex Officio), Society for the Improvement of Psychological Science \hfill 2022  
Project Manager, Framework for Open and Reproducible Research Training (FORRT) \hfill 2021-present  
Affiliate, Stanford Center for Open and Reproducible Science \hfill 2020-present  

# LANGUAGES

Dutch, English, R, R Markdown, Quarto, Git/GitHub, \LaTeX, SAS

# PROFESSIONAL MEMBERSHIPS

Academy of Management  
Psychological Science Accelerator  
Society for Judgment and Decision Making  
Society for Personality and Social Psychology  
Society for the Improvement of Psychological Science  

# PREVIOUS RESEARCH AND TEACHING POSITIONS

INSEAD-Sorbonne Behavioral Lab, INSEAD Marketing Department \hfill 2017-2018  
Harvard Psychology Department and Kennedy School of Government \hfill Summer 2017  
Decision Processes Lab, Wharton School of Business \hfill Fall 2016  
Erasmus School of Economics \hfill Summer 2013, 2015-2016  
Social and Behavioral Sciences Department, Erasmus University College \hfill 2014-2015  

<!-- # References -->
